%YAML 1.2
---
port: 8888
settings:
    app_uri: https://uscheduler.herokuapp.com
    db_uri: StudentScheduler
    cookie_secret: your_cookie_secret
    static_path: static
    template_path: static
    static_url_prefix: '.'
    twitter_consumer_key: twi_key
    twitter_consumer_secret: twi_secret
    facebook_api_key: fb_key
    facebook_secret: fb_secret
    google_oauth:
        key: 571482470120-gulh6a8qqf0kfgf1rqqeula5mgk8v698.apps.googleusercontent.com
        secret: e2WRcVq09OEHwDAtsvy5Ks_e
    login_url: /login
    debug: True
